from __future__ import annotations

from typing import List

from .knowledge_base import NoteChunk
from .schemas import SophiaResponse, SourceType


class LLMClient:
    """
    Placeholder LLM client.

    For now, it constructs a SophiaResponse with stub content.
    Later, you can call a real LLM API or local model here.
    """

    def build_prompt(self, question: str, topic: str, notes: List[NoteChunk]) -> str:
        notes_text = "\n\n---\n\n".join(
            f"Source: {n.source}\n{n.text}" for n in notes
        ) or "(no notes found for this topic)"

        return (
            f"You are Sophia, an interview coach for ML / LLM roles.\n"
            f"Topic: {topic}\n"
            f"Question: {question}\n\n"
            f"Use the notes below to:\n"
            f"1. Answer the question in a clear, technical way.\n"
            f"2. Explain the idea simply.\n"
            f"3. Propose one follow-up question.\n\n"
            f"NOTES:\n{notes_text}\n"
        )

    def ask(self, question: str, topic: str, notes: List[NoteChunk]) -> SophiaResponse:
        """
        Stub implementation.

        Returns a structured response that echoes the inputs,
        so you can test the pipeline end-to-end.
        """
        source_type: SourceType = "personal_notes" if notes else "model_only"
        prompt = self.build_prompt(question, topic, notes)

        technical_answer = (
            "This is a placeholder technical answer generated by the stub LLMClient.\n\n"
            "In a real setup, this text would come from an LLM API call using a prompt "
            "similar to the one constructed internally."
        )
        simple_explanation = (
            "Simple explanation: right now this is a stub. Once you connect a real LLM, "
            "this will explain the concept in plain language."
        )
        follow_up_question = "Follow-up: what trade-offs would you mention if asked this in a real interview?"

        # In case you want to debug prompts
        technical_answer += f"\n\n[DEBUG PROMPT SNIPPET]\n{prompt[:400]}..."

        return SophiaResponse(
            topic=topic,
            source_type=source_type,
            technical_answer=technical_answer,
            simple_explanation=simple_explanation,
            follow_up_question=follow_up_question,
        )
